baseURL = '/'
languageCode = 'en-us'
title = 'Empirical reporting'
theme = "myflatly"


relativeURLs = false
description = "Website for the data reporting class at the Cronkite School for investigative reporting masters' students, Spring 2022"
# publishDir = "docs"

[menu]

  [[menu.main]]
     name = "Syllabus"
     url = "/syllabus.html/"


  [[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule.html"


   [[menu.main]]
    identifier = "weeks"
    name = "Week details"
    url = "#"
    isParent = true
    hasChildren = true




   [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"


   [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"


  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = false
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = false
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
    [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startlevel = 2

[taxonomies]
   series = "series"