#baseURL="/"
baseURL = 'https://cronkitedata.github.io/dataj'
languageCode = 'en-us'
title = 'Empirical reporting'
theme = "myflatly"
# I think this affects whether you use bundles or not. I'm very confused about this and need to check it before going much further.
relativeURLs = false
description = "Website for the data reporting class at the Cronkite School for investigative reporting masters' students, Spring 2022"
publishDir = "docs"

#NOTE: Need to have baseurl without the / at the end and relativeURLs false. 
# then if you want to see it locally, go to localhost:1313/dataj/ and the links appear to work. 



[[menu.main]]
    identifier = "syllabus"
    name = "Syllabus"
    url = "/syllabus/"
    weight = 1

[[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule/"
    weight= 2

[[menu.main]]
    identifier = "weeks"
    name = "Week details"
    url = "/weeks/"
    weight = 3

  
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight =  9

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/coursedocs/"
    hasChildren = true
    weight = 4

[[menu.main]]
    identifier = "replication"
    name = "Replication project"
    url = "/coursedocs/replication/"
    weight =  1
    parent = "projects"

[[menu.main]]
    identifier = "memo"
    name = "Story memo"
    url = "/coursedocs/memo/"
    weight =  2
    parent =  "projects"

[[menu.main]]
    identifier = "explainer"
    name = "Explainer"
    url = "/coursedocs/explainer/"
    weight =  4
    parent =  "projects"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = false
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = false
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
    [markup.tableOfContents]
      endLevel = 4
      ordered = false
      startlevel = 2

[taxonomies]
   series = "series"